name: Substack Summary Cron Job

on:
  schedule:
    # This cron syntax runs the job every day at 7:00 AM UTC
    - cron: "30 1 * * *"

jobs:
  run_substack_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Substack Summary script
        run: |
          python final_substack_reader.py
