name: Substack Summary Cron Job

on:
  schedule:
    #- cron: '30 1 * * *'  # 7:00 AM IST (which is 1:30 AM UTC)
    - cron: '*/5 * * * *'
  workflow_dispatch:  # allows manual run

jobs:
  run-summary:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Echo Cron Job Triggered
        run: echo "Cron job triggered at $(date)"
        
      - name: Run Substack Summary Script
        run: python final_substack_reader.py
